[tools]
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:gotest.tools/gotestsum" = "latest"

[tasks.test]
description = "Run all 2025 tests"
run = "gotestsum --format pkgname"

[tasks."test:watch"]
description = "Run all 2025 tests"
run = "gotestsum --format pkgname --watch"
