name: "2025"
on:
  push:
    paths:
      - "2025/**"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25" # use your Go version

      # Download dependencies
      - name: Install dependencies
        run: cd 2025 && go mod tidy

      - name: Setup gotestsum
        uses: autero1/action-gotestsum@v2.0.0
        with:
          gotestsum_version: 1.13.0

      - name: Run tests with gotestsum
        run: cd 2025 && gotestsum --format short-verbose --junitfile unit-tests.xml ./...

      - name: Upload test summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: "./2025/unit-tests.xml"
